"""
NOTE: this code was generated by Claude
Cortex-M0+ Cycle Estimator for the TI MSPM0L2228
=================================================

Sources
-------
- ARM DDI 0484C  - Cortex-M0+ TRM, Table 3.1 (instruction cycle counts)
- TI SLASF94A    - MSPM0L2228 Datasheet:
    §7.3 page 43: "f_MCLK with 1 flash wait state — MAX 32 MHz"
                  "f_MCLK with 0 flash wait states — MAX 24 MHz"
                  Footnote 3: "Wait states managed automatically by SYSCTL"
    §8.11: "SRAM has zero wait state access across the supported CPU
            frequency range"

Flash wait states at 32 MHz: 1
SRAM wait states: 0

Pipeline model
--------------
The Cortex-M0+ has a 2-stage von-Neumann pipeline (Fetch + Execute).
With 1 wait state the flash fetch bus takes 2 cycles per 16-bit word.
The 2-stage pipeline overlaps one fetch with one execute, so for
sequential code the single wait state is entirely hidden — no stall.

When the pipeline is flushed (any taken branch / call / return) the
prefetch buffer is discarded and the branch-target fetch pays the full
1-cycle wait-state penalty.

Bounds
------
Three sources of per-instruction uncertainty are tracked separately so
that a lower bound and upper bound can be returned alongside the best
estimate:

1. MUL (MULS): 1 cycle (single-cycle impl.) vs 32 cycles (32-cycle impl.)
   The MSPM0L2228 TRM documents both variants; the low-area 32-cycle
   variant is the default. The caller can override the best estimate via
   mul_single_cycle, but bounds always span the full [1, 32] range.

2. Load/Store to AHB peripherals: base cost is 2 cycles (Table 3.1 note [b]:
   "2 if to AHB interface or SCS, 1 if to single-cycle I/O port").
   The single-cycle I/O port (IOSC) gives 1 cycle for GPIO; other AHB
   peripherals are always 2.  We don't know the target at static analysis
   time, so lower=1, upper=2 for loads/stores.

3. Taken-branch flash penalty: the pipeline has NO prefetch cache on this
   device.  However, a branch that targets the same 32-bit-aligned flash
   word that is already staged in the pipeline (e.g. a very tight 2-insn
   loop) may avoid the 1-cycle stall.
   Lower bound: 0 stall on branch (best case — target already fetched).
   Upper bound: 1 stall on branch (normal case — pipeline flushed).
   Best estimate: 1 stall (conservative, matches the non-cached pipeline).
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

from capstone import CsInsn
from capstone.arm import (
    ARM_INS_LDM, ARM_INS_STM, ARM_INS_PUSH, ARM_INS_POP,
    ARM_INS_LDR, ARM_INS_LDRB, ARM_INS_LDRH, ARM_INS_LDRSB, ARM_INS_LDRSH,
    ARM_INS_STR, ARM_INS_STRB, ARM_INS_STRH,
    ARM_INS_B, ARM_INS_BL, ARM_INS_BX, ARM_INS_BLX,
    ARM_INS_CBZ, ARM_INS_CBNZ,
    ARM_INS_MUL,
    ARM_INS_ISB, ARM_INS_DSB, ARM_INS_DMB,
    ARM_INS_WFI, ARM_INS_WFE,
    ARM_INS_MRS, ARM_INS_MSR,
    ARM_INS_SVC,
    ARM_INS_NOP,
    ARM_OP_REG,
)
try:
    from capstone.arm_const import ARM_REG_PC
except ImportError:
    ARM_REG_PC = 15  # R15 is always PC on ARM

# ─────────────────────────────────────────────────────────────────────────────
# Device constants
# ─────────────────────────────────────────────────────────────────────────────

CLOCK_HZ = 32_000_000  # 32 MHz

FLASH_BASE = 0x0000_0000
FLASH_END  = 0x0003_FFFF  # 256 KB main flash

SRAM_BASE  = 0x2000_0000
SRAM_END   = 0x2007_FFFF  # 32 KB SRAM

# Flash wait states at 32 MHz (datasheet §7.3)
FLASH_WAIT_STATES = 1

# ─────────────────────────────────────────────────────────────────────────────
# Result type
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class CycleEstimate:
    """
    Cycle-count estimate with lower and upper bounds.

    lower  - minimum plausible cycles (best case: MUL=1, loads=1-cycle I/O,
             taken branches hit pre-staged pipeline word)
    best   - most-likely cycles (MUL=32, loads=2, branch flush always pays
             the wait-state penalty)
    upper  - maximum plausible cycles (same as best; see note on WFI/WFE/SVC)

    Note: WFI, WFE, and SVC have unbounded upper costs due to waiting /
    exception entry.  upper only reflects the cost of the instruction itself
    in those cases; callers should add domain-specific overhead separately.
    """
    lower: int
    best:  int
    upper: int

    def __str__(self) -> str:
        return f"CycleEstimate(lower={self.lower}, best={self.best}, upper={self.upper})"

    def to_microseconds(self, clock_hz: int = CLOCK_HZ) -> tuple[float, float, float]:
        """Return (lower_us, best_us, upper_us)."""
        s = 1e6 / clock_hz
        return self.lower * s, self.best * s, self.upper * s


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _is_flash(addr: int) -> bool:
    return FLASH_BASE <= addr <= FLASH_END


def _reg_count(insn: CsInsn) -> int:
    """
    Count register operands.  Works whether or not Capstone was opened with
    detail=True.  When detail is unavailable (CS_ERR_DETAIL) we fall back to
    parsing op_str.

    For PUSH / POP / LDM / STM the operands are a brace-enclosed list such as
    "{r4, r5, lr}" — we count tokens inside the braces.
    For all other instructions we count the leading comma-separated register
    tokens before any "[" memory address expression.
    """
    try:
        return sum(1 for op in insn.operands if op.type == ARM_OP_REG)
    except Exception:
        import re
        op = insn.op_str.lower()
        # Brace list: PUSH / POP / LDM / STM
        brace = re.search(r'\{([^}]*)\}', op)
        if brace:
            return len(re.findall(
                r'\b(?:r\d{1,2}|sp|lr|pc|fp|ip|sl|sb)\b',
                brace.group(1)
            ))
        # Plain register list: count regs before any '[' (memory operand)
        before_mem = op.split('[')[0]
        return len(re.findall(
            r'\b(?:r\d{1,2}|sp|lr|pc|fp|ip|sl|sb)\b',
            before_mem
        ))


def _has_pc(insn: CsInsn) -> bool:
    """
    Return True if PC (R15) is one of the register operands.
    Falls back to op_str inspection when detail mode is unavailable.
    """
    try:
        for op in insn.operands:
            if op.type == ARM_OP_REG and op.reg == ARM_REG_PC:
                return True
        return False
    except Exception:
        # detail mode is off — check op_str for 'pc' as a whole word
        import re
        return bool(re.search(r'\bpc\b', insn.op_str.lower()))


def _taken(insn: CsInsn, next_insn: Optional[CsInsn]) -> bool:
    if next_insn is None:
        return True
    return next_insn.address != insn.address + insn.size


# ─────────────────────────────────────────────────────────────────────────────
# Per-instruction bounds
#
# Returns (lower, best, upper) all at zero-wait-state, before flash penalty.
# ─────────────────────────────────────────────────────────────────────────────

def _insn_bounds(insn: CsInsn, next_insn: Optional[CsInsn]) -> tuple[int, int, int]:
    """
    Return (lower, best, upper) zero-wait-state cycle counts for one insn.

    Sources of asymmetry:
      MUL:          lower=1  (single-cycle variant)
                    best/upper=32 (32-cycle low-area variant, MSPM0 default)
      LDR/STR:      lower=1  (single-cycle I/O port, note [b] in Table 3.1)
                    best/upper=2 (AHB interface / SRAM, which is the normal case)
    Everything else has lower == best == upper.
    """
    iid = insn.id

    # ── Branches ──────────────────────────────────────────────────────────
    if iid == ARM_INS_BL:
        return 3, 3, 3
    if iid in (ARM_INS_BX, ARM_INS_BLX):
        return 2, 2, 2
    if iid in (ARM_INS_B, ARM_INS_CBZ, ARM_INS_CBNZ):
        c = 2 if _taken(insn, next_insn) else 1
        return c, c, c

    # ── Stack multiple ─────────────────────────────────────────────────────
    if iid == ARM_INS_PUSH:
        n = max(_reg_count(insn), 1)
        c = 1 + n
        return c, c, c
    if iid == ARM_INS_POP:
        n = max(_reg_count(insn), 1)
        if _has_pc(insn):
            c = 3 + n
        else:
            c = 1 + n
        return c, c, c

    # ── Load/Store multiple ────────────────────────────────────────────────
    if iid in (ARM_INS_LDM, ARM_INS_STM):
        n = max(_reg_count(insn) - 1, 1)
        c = 1 + n
        return c, c, c

    # ── Single loads ──────────────────────────────────────────────────────
    # lower=1 (single-cycle I/O port), best/upper=2 (AHB / SRAM)
    if iid in (ARM_INS_LDR, ARM_INS_LDRB, ARM_INS_LDRH,
               ARM_INS_LDRSB, ARM_INS_LDRSH):
        return 1, 2, 2

    # ── Stores ────────────────────────────────────────────────────────────
    if iid in (ARM_INS_STR, ARM_INS_STRB, ARM_INS_STRH):
        return 1, 2, 2

    # ── Multiply ──────────────────────────────────────────────────────────
    # lower=1 (single-cycle impl.), best/upper=32 (32-cycle low-area impl.)
    if iid == ARM_INS_MUL:
        return 1, 32, 32

    # ── Barriers / special registers ──────────────────────────────────────
    if iid in (ARM_INS_ISB, ARM_INS_DSB, ARM_INS_DMB):
        return 3, 3, 3
    if iid in (ARM_INS_MRS, ARM_INS_MSR):
        return 3, 3, 3

    # ── Hints ─────────────────────────────────────────────────────────────
    if iid in (ARM_INS_WFI, ARM_INS_WFE):
        # Instruction-only cost; actual wait time is unbounded and excluded.
        return 2, 2, 2
    if iid == ARM_INS_SVC:
        # Instruction-only; exception entry (~15 cycle stacking) excluded.
        return 2, 2, 2

    # ── Default 1-cycle ALU ───────────────────────────────────────────────
    return 1, 1, 1


def _flushes_pipeline(insn: CsInsn, next_insn: Optional[CsInsn]) -> bool:
    iid = insn.id
    if iid in (ARM_INS_BL, ARM_INS_BX, ARM_INS_BLX):
        return True
    if iid in (ARM_INS_B, ARM_INS_CBZ, ARM_INS_CBNZ):
        return _taken(insn, next_insn)
    if iid == ARM_INS_POP and _has_pc(insn):
        return True
    if iid == ARM_INS_LDR and _has_pc(insn):
        return True
    return False


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def estimate_cycles(
    instructions: list[CsInsn],
    *,
    verbose: bool = False,
) -> CycleEstimate:
    """
    Estimate lower, best, and upper cycle counts for a Cortex-M0+ execution
    trace on the TI MSPM0L2228 (32 MHz, 1 flash wait state, no cache).

    Parameters
    ----------
    instructions : list[CsInsn]
        Ordered list of *executed* instructions (execution order, not binary
        order) as returned by Capstone.
    verbose : bool
        Print a per-instruction breakdown when True.

    Returns
    -------
    CycleEstimate
        .lower  — best-case total (MUL=1 cycle, loads=1 cycle I/O port,
                  taken branches hit pre-staged flash word → no stall)
        .best   — most-likely total (MUL=32 cycles, loads=2 cycles,
                  taken branch pays 1-cycle flash flush penalty)
        .upper  — worst-case total (same as best for deterministic insns;
                  WFI/WFE/SVC instruction cost only — actual wait time
                  excluded as it is unbounded / system-dependent)

    Accuracy notes
    --------------
    * Flash: 1 wait state at 32 MHz (datasheet §7.3). The 2-stage M0+
      pipeline hides this for sequential code. Taken branches expose it.
    * SRAM: zero wait states (datasheet §8.11). No penalty modelled.
    * AHB peripheral latency beyond the 2-cycle base is not modelled.
    * Interrupt/exception entry latency (~15 cycles of hardware stacking)
      is excluded from all three bounds.
    """
    total_lo = total_best = total_hi = 0

    if verbose:
        print(f"  {'Address':10}  {'Mnemonic':8}  {'Operands':26}  "
              f"{'lo':>4}  {'best':>4}  {'hi':>4}  Notes")
        print("  " + "-" * 75)

    for i, insn in enumerate(instructions):
        next_insn = instructions[i + 1] if i + 1 < len(instructions) else None

        # 1. Zero-wait-state bounds from ARM DDI 0484C Table 3.1
        lo, best, hi = _insn_bounds(insn, next_insn)

        # 2. Flash wait-state penalty (only for instructions fetched from flash)
        notes = []
        if _is_flash(insn.address):
            if _flushes_pipeline(insn, next_insn):
                # best/upper: pipeline is flushed, 1 wait state fully exposed → +1
                # lower: branch target may already be staged (tight loop) → +0
                best += 1
                hi   += 1
                notes.append("branch flush (+0/+1)")
            # Sequential flash: pipeline hides wait state for all three bounds → +0

        if verbose:
            note_str = ", ".join(notes) if notes else ""
            print(f"  0x{insn.address:08x}  {insn.mnemonic:<8}  {insn.op_str:<26}  "
                  f"{lo:4d}  {best:4d}  {hi:4d}  {note_str}")

        total_lo   += lo
        total_best += best
        total_hi   += hi

    return CycleEstimate(lower=total_lo, best=total_best, upper=total_hi)


def cycles_to_microseconds(cycles: int, clock_hz: int = CLOCK_HZ) -> float:
    """Convert a cycle count to microseconds."""
    return cycles / clock_hz * 1e6


# ─────────────────────────────────────────────────────────────────────────────
# Self-test
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import types

    def _mock(iid, addr, mnemonic, op_str="", size=2, operands=None):
        ins = types.SimpleNamespace()
        ins.id, ins.address  = iid, addr
        ins.mnemonic, ins.op_str = mnemonic, op_str
        ins.size     = size
        ins.operands = operands or []
        return ins

    def _reg(rid):
        return types.SimpleNamespace(type=ARM_OP_REG, reg=rid)

    trace = [
        # ── Sequential flash ──────────────────────────────────────────────
        # ALU: lo=best=hi=1, no flash stall
        _mock(1,           0x0000_0100, "movs",  "r0, #0"),
        _mock(1,           0x0000_0102, "adds",  "r1, r0, r0"),
        # LDR: lo=1, best=hi=2, no flash stall (seq)
        _mock(ARM_INS_LDR, 0x0000_0104, "ldr",   "r2, [r0, #4]"),
        # STR: lo=1, best=hi=2, no flash stall
        _mock(ARM_INS_STR, 0x0000_0106, "str",   "r2, [r1, #0]"),
        # MUL: lo=1, best=hi=32, no flash stall (seq)
        _mock(ARM_INS_MUL, 0x0000_0108, "muls",  "r0, r1, r0"),
        # BL from flash: base=3, lo stall=+0, best/hi stall=+1 → lo=3, best=hi=4
        _mock(ARM_INS_BL,  0x0000_010A, "bl",    "some_func"),
        # B taken from flash: base=2, lo=+0, best/hi=+1 → lo=2, best=hi=3
        _mock(ARM_INS_B,   0x0000_010E, "b",     "0x100"),
        # POP {r4,r5,pc}: base=3+3=6, lo=+0, best/hi=+1 → lo=6, best=hi=7
        _mock(ARM_INS_POP, 0x0000_0112, "pop",   "{r4,r5,pc}",
              operands=[_reg(4), _reg(5), _reg(ARM_REG_PC)]),
        # ── SRAM: no flash stall on any bound ─────────────────────────────
        # ALU: lo=best=hi=1
        _mock(1,           0x2000_0000, "movs",  "r3, #5"),
        # MUL from SRAM: lo=1, best=hi=32
        _mock(ARM_INS_MUL, 0x2000_0002, "muls",  "r3, r3, r3"),
        # ISB: lo=best=hi=3
        _mock(ARM_INS_ISB, 0x2000_0004, "isb",   ""),
    ]

    #                        lo   best   hi
    # movs  (flash, seq)      1     1     1
    # adds  (flash, seq)      1     1     1
    # ldr   (flash, seq)      1     2     2
    # str   (flash, seq)      1     2     2
    # muls  (flash, seq)      1    32    32
    # bl    (flash, flush)    3     4     4
    # b     (flash, flush)    2     3     3
    # pop   (flash, flush)    6     7     7
    # movs  (sram)            1     1     1
    # muls  (sram)            1    32    32
    # isb   (sram)            3     3     3
    # ─────────────────────────────────────
    # totals                 21    88    88
    expected = (21, 88, 88)

    print("Per-instruction breakdown:")
    result = estimate_cycles(trace, verbose=True)
    lo_us, best_us, hi_us = result.to_microseconds()
    print(f"\nResult   : {result}")
    print(f"Expected : CycleEstimate(lower={expected[0]}, best={expected[1]}, upper={expected[2]})")
    assert (result.lower, result.best, result.upper) == expected, "SELF-TEST FAILED"
    print("Self-test PASSED ✓")
    print(f"\nAt 32 MHz:")
    print(f"  Lower : {lo_us:.3f} µs")
    print(f"  Best  : {best_us:.3f} µs")
    print(f"  Upper : {hi_us:.3f} µs")